### ISSUE TITLE
ENOTDIR error 

### ISSUE THREAD

**Issue by Incongruous2358** [chegele/BDSAddonInstaller#11]
I have tried different file paths and i keep getting this error i have followed the basic command line instructions and tried multiple installed servers  
Error: ENOTDIR: not a directory, scandir 'C:\Users\jmdef\Desktop\bedrock-server-1.19.51.01\behavior_packs\.gitignore'
    at Object.readdirSync (node:fs:1451:3)
    at findFilesSync (file:///C:/Users/jmdef/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:572:25)
    at file:///C:/Users/jmdef/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:483:32
    at Array.forEach (<anonymous>)
    at mapInstalledPacks (file:///C:/Users/jmdef/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:478:20)
    at new BDSAddonInstaller (file:///C:/Users/jmdef/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:99:36)
    at file:///C:/Users/jmdef/AppData/Roaming/npm/node_modules/bds-addon-installer/cli.js:76:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -4052,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: 'C:\\Users\\jmdef\\Desktop\\bedrock-server-1.19.51.01\\behavior_packs\\.gitignore'

**Comment by chegele** [comment]
Try removing this file

C:\Users\jmdef\Desktop\bedrock-server-1.19.51.01\behavior_packs.gitignore

**Comment by Incongruous2358** [comment]
Worked thanks
