### ISSUE TITLE
Not a directory error

### ISSUE THREAD

**Issue by StrickenAza34** [chegele/BDSAddonInstaller#12]
```
Microsoft Windows [Version 10.0.20348.1726]
(c) Microsoft Corporation. All rights reserved.

E:\Minecraft Server\The Duat>bds-addon-installer

Running Bedrock Dedicated Server Addon Installer...
node:fs:1452
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, scandir 'E:\Minecraft Server\The Duat\worlds\The Duat\resource_packs\desktop.ini'
    at Object.readdirSync (node:fs:1452:3)
    at findFilesSync (file:///C:/Users/Aza/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:572:25)
    at file:///C:/Users/Aza/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:483:32
    at Array.forEach (<anonymous>)
    at mapInstalledPacks (file:///C:/Users/Aza/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:478:20)
    at new BDSAddonInstaller (file:///C:/Users/Aza/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:100:35)
    at file:///C:/Users/Aza/AppData/Roaming/npm/node_modules/bds-addon-installer/cli.js:76:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -4052,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: 'E:\\Minecraft Server\\The Duat\\worlds\\The Duat\\resource_packs\\desktop.ini'
}

Node.js v18.16.0
```

**Comment by MaezrFulldive** [comment]
I just had the same problem, I had a file that was not a directory in the resource pack folder, you need to remove the desktop.ini file and it will work    ; )
