### ISSUE TITLE
Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by chkwon** [chegele/BDSAddonInstaller#4]
```bash
C:\Users\user_name\Documents\bedrockserver>bds-addon-installer -r -v

Running Bedrock Dedicated Server Addon Installer...
[6/20/2020, 9:27:57 PM] DETAIL  BDSAddonInstaller - Reading world name from C:\Users\user_name\Documents\bedrockserver\server.properties
[6/20/2020, 9:27:57 PM] DETAIL  BDSAddonInstaller - Reading manifest data from C:\Users\user_name\Documents\bedrockserver\resource_packs\._chemistry
fs.js:974
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, scandir 'C:\Users\user_name\Documents\bedrockserver\resource_packs\._chemistry'
    at Object.readdirSync (fs.js:974:3)
    at findFilesSync (file:///C:/Users/user_name/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:571:25)
    at file:///C:/Users/user_name/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:482:32
    at Array.forEach (<anonymous>)
    at mapInstalledPacks (file:///C:/Users/user_name/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:477:20)
    at new BDSAddonInstaller (file:///C:/Users/user_name/AppData/Roaming/npm/node_modules/bds-addon-installer/index.js:97:36)
    at file:///C:/Users/user_name/AppData/Roaming/npm/node_modules/bds-addon-installer/cli.js:76:19
    at ModuleJob.run (internal/modules/esm/module_job.js:138:23)
    at async Loader.import (internal/modules/esm/loader.js:178:24) {
  errno: -4052,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: 'C:\\Users\\user_name\\Documents\\bedrockserver\\resource_packs\\._chemistry'
}
```

The actual folder name is `resource_packs\\chemistry`, without `._` 

Node.js version was `14.3.0`
BDS version was `1.14.60.5`

**Comment by chegele** [comment]
I'm having trouble replicating this issue on bedrock-server-1.14.60.5. Can you provide the full dir contents of the resources folder as well as the text in valid_known_packs.json? 

Resources: C:\Users\user_name\Documents\bedrockserver\resource_packs\
Valid Packs: C:\Users\user_name\Documents\bedrockserver\valid_known_packs.json

**Comment by chkwon** [comment]
There are only two subdirectories within `resource_packs`:  `chemistry` and `vanilla`. There are no hidden directories or anything that starts with `._` 

I modified your script to skip anything that starts with `._`, then it worked fine. But quite strange. 

It goes over all variants such as `._chemistry`, `._vanilla`, `._test_vanilla_1.11`, and so on.

Here is `valid_known_packs.json`:
```json

[
	
	{
		"file_version" : 2
	},
	
	{
		"file_system" : "RawPath",
		"from_disk" : true,
		"hashes" : 
		[
			"4XYf+lxO5eSNo8DR+ILg/HZAVZh9tSg56LZY0yeBL28=",
			"FtpolfWOT1V7pyJDmqV3SHYSbiXJHoyaJyf4ux3liaw="
		],
		"path" : "behavior_packs/test_vanilla_1.11",
		"uuid" : "fe9f8597-5454-481a-8730-8d070a8e2e58",
		"version" : "1.11.0"
	},
	
	{
		"file_system" : "RawPath",
		"path" : "resource_packs/vanilla",
		"uuid" : "0575c61f-a5da-4b7f-9961-ffda2908861e",
		"version" : "0.0.1"
	},
	
	{
		"file_system" : "RawPath",
		"path" : "resource_packs/chemistry",
		"uuid" : "0fba4063-dba1-4281-9b89-ff9390653530",
		"version" : "1.0.0"
	},

	{
		"file_system" : "RawPath",
		"path" : "behavior_packs/vanilla_1.14",
		"uuid" : "fe9f8597-5454-481a-8730-8d070a8e2e58",
		"version" : "1.14.0"
	},

       {
		"file_system" : "RawPath",
		"path" : "behavior_packs/vanilla",
		"uuid" : "fe9f8597-5454-481a-8730-8d070a8e2e58",
		"version" : "0.0.1"
	},
	
	{
		"file_system" : "RawPath",
		"path" : "behavior_packs/vanilla_experimental",
		"uuid" : "47db1a44-55b4-4d4e-aa0f-d5de6206a0fd",
		"version" : "0.0.1"
	},
	
	{
		"file_system" : "RawPath",
		"path" : "behavior_packs/chemistry",
		"uuid" : "6baf8b62-8948-4c99-bb1e-a0cb35dc4579",
		"version" : "1.0.0"
	},
	
	{
		"file_system" : "RawPath",
		"from_disk" : true,
		"hashes" : 
		[
			"NsOhIUmhR0mVHFAq2Yh+z6lAY9M8UuFoOIyxoc84c8Q=",
			"dDIeWfuadZSJkYYfmhQMgyavQ91ozF3pn7201qiJVDs="
		],
		"path" : "behavior_packs/test_vanilla_1.12",
		"uuid" : "fe9f8597-5454-481a-8730-8d070a8e2e58",
		"version" : "1.12.0"
	}
]
```

**Comment by chegele** [comment]
I'm having a hard time determining where it is finding files or folders with  "._" appended to the beginning of the names. I could implement a blind fix of skipping those files, but i would prefer to understand the cause. 

Would you be willing to upload a zip of your bds?

**Comment by chkwon** [comment]
It seems like my folder was corrupted somehow. I started over with a fresh install of the server and it didn't happen. Strange. But your code works fine. Thanks for working on it. I appreciate your time.
